apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firemanm-ingress
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /otus/(.*)/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lab001v2-svc
            port:
              number: 80

      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lab001v2-svc
            port:
              number: 80